import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";

// --- Mocks for all heavy dependencies ---
// vi.hoisted ensures these are available before vi.mock factories execute

const {
  mockCloseStream,
  mockCancelForTask,
  mockBroadcastTaskUpdate,
  mockBroadcastTaskRemoval,
  mockSetProviders,
} = vi.hoisted(() => ({
  mockCloseStream: vi.fn(),
  mockCancelForTask: vi.fn(),
  mockBroadcastTaskUpdate: vi.fn(),
  mockBroadcastTaskRemoval: vi.fn(),
  mockSetProviders: vi.fn(),
}));

vi.mock("../sse/manager.js", () => ({
  sseManager: {
    closeStream: (...args: any[]) => mockCloseStream(...args),
  },
}));
vi.mock("../lib/question-manager.js", () => ({
  questionManager: {
    cancelForTask: (...args: any[]) => mockCancelForTask(...args),
  },
}));
vi.mock("../agent/query-tracker.js", () => ({
  cancelTask: vi.fn(),
}));
vi.mock("../lib/logger.js", () => ({
  taskLogger: () => ({
    info: vi.fn(),
    warn: vi.fn(),
    error: vi.fn(),
    debug: vi.fn(),
  }),
}));
vi.mock("../lib/safe-fire.js", () => ({
  safeFire: vi.fn(),
}));
vi.mock("../sse/task-list-broadcaster.js", () => ({
  taskListBroadcaster: {
    broadcastTaskUpdate: (...args: any[]) => mockBroadcastTaskUpdate(...args),
    broadcastTaskRemoval: (...args: any[]) => mockBroadcastTaskRemoval(...args),
    setProviders: (...args: any[]) => mockSetProviders(...args),
  },
}));
vi.mock("./persistence.js", () => ({
  persistSnapshot: vi.fn().mockResolvedValue(undefined),
  flushSnapshotSync: vi.fn(),
  loadSnapshot: vi.fn().mockReturnValue(undefined),
  snapshotPath: vi.fn().mockReturnValue("/tmp/fake-snapshot.json"),
  pipelineFingerprint: vi.fn().mockReturnValue("fp-123"),
}));
vi.mock("./side-effects.js", () => ({
  registerSideEffects: vi.fn(),
}));
vi.mock("./workflow-lifecycle.js", () => ({
  snapshotGlobalConfig: vi.fn().mockReturnValue({
    pipelineName: "test",
    pipeline: {
      name: "test",
      stages: [
        { name: "plan", type: "agent", runtime: { engine: "claude", max_turns: 3, budget_usd: 1 } },
      ],
    },
    prompts: {
      system: {},
      fragments: {},
      globalConstraints: "",
      globalClaudeMd: "",
      globalGeminiMd: "",
        globalCodexMd: "",
    },
    skills: [],
    mcps: [],
  }),
}));
vi.mock("./machine.js", () => {
  const { setup, assign } = require("xstate");
  const trivialSetup = setup({
    types: { context: {} as any, events: {} as any, emitted: {} as any },
  });
  return {
    createWorkflowMachine: vi.fn().mockReturnValue(
      trivialSetup.createMachine({
        id: "workflow",
        initial: "idle",
        context: {
          taskId: "",
          status: "idle",
          retryCount: 0,
          qaRetryCount: 0,
          stageSessionIds: {},
          store: {},
        },
        states: {
          idle: {
            on: {
              START_ANALYSIS: {
                actions: assign(({ event }: any) => ({
                  taskId: event.taskId,
                })),
              },
              LAUNCH: { target: "plan" },
            },
          },
          plan: {
            entry: assign({ status: "plan" }),
            on: {
              CONFIRM: { target: "completed" },
            },
          },
          completed: { type: "final" },
          error: { type: "final" },
          blocked: {},
          cancelled: {},
        },
      }),
    ),
  };
});
vi.mock("../lib/config-loader.js", () => ({
  loadPipelineConfig: vi.fn(),
  getNestedValue: vi.fn(),
}));

import {
  getWorkflow,
  getAllWorkflows,
  sendEvent,
  createTaskDraft,
  launchTask,
  startWorkflow,
  deleteWorkflow,
  restoreWorkflow,
  sweepStaleActors,
  stopSweepTimer,
} from "./actor-registry.js";
import type { WorkflowActor } from "./actor-registry.js";
import { flushSnapshotSync } from "./persistence.js";

describe("actor-registry", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    vi.useFakeTimers();
    // Clean up any leftover actors from previous tests
    for (const [id] of getAllWorkflows()) {
      deleteWorkflow(id);
    }
    vi.clearAllMocks(); // clear mocks generated by cleanup
  });

  afterEach(() => {
    vi.useRealTimers();
  });

  // --- getWorkflow for non-existent taskId ---

  it("getWorkflow returns undefined for a non-existent taskId", () => {
    expect(getWorkflow("nonexistent-task-999")).toBeUndefined();
  });

  // --- sendEvent to non-existent actor ---

  it("sendEvent returns false for a non-existent taskId", () => {
    expect(sendEvent("nonexistent-task-999", { type: "CANCEL" })).toBe(false);
  });

  // --- createTaskDraft registers an actor ---

  it("createTaskDraft registers an actor retrievable via getWorkflow", () => {
    const actor = createTaskDraft("task-1");
    expect(actor).toBeDefined();
    expect(getWorkflow("task-1")).toBe(actor);
  });

  // --- launchTask for non-existent actor ---

  it("launchTask returns false for a non-existent taskId", () => {
    expect(launchTask("ghost-task")).toBe(false);
  });

  // --- launchTask transitions actor from idle ---

  it("launchTask returns true and transitions actor out of idle", () => {
    createTaskDraft("task-launch");
    const result = launchTask("task-launch");
    expect(result).toBe(true);
    const snap = getWorkflow("task-launch")!.getSnapshot();
    expect(snap.value).not.toBe("idle");
  });

  // --- sendEvent to existing actor ---

  it("sendEvent returns true for an existing actor", () => {
    createTaskDraft("task-evt");
    expect(sendEvent("task-evt", { type: "CANCEL" })).toBe(true);
  });

  // --- deleteWorkflow removes actor and closes SSE ---

  it("deleteWorkflow removes the actor, closes SSE stream, and cancels questions", () => {
    createTaskDraft("task-del");
    expect(getWorkflow("task-del")).toBeDefined();

    deleteWorkflow("task-del");

    expect(getWorkflow("task-del")).toBeUndefined();
    expect(mockCloseStream).toHaveBeenCalledWith("task-del");
    expect(mockCancelForTask).toHaveBeenCalledWith("task-del");
    expect(mockBroadcastTaskRemoval).toHaveBeenCalledWith("task-del");
  });

  // --- scheduleActorCleanup: non-done actor not deleted ---

  it("scheduleActorCleanup does not delete a non-done actor after delay", () => {
    const actor = createTaskDraft("task-alive");
    // Actor is in "idle" state (status !== "done"), trigger cleanup by simulating done
    // Actually, the actor stays alive because its xstate status is "active", not "done"
    // We need to trigger the subscription callback that calls scheduleActorCleanup.
    // Instead, let's test indirectly: the actor should still be present after the timer
    // because its xstate .status is not "done".

    // Force the internal setTimeout path by calling the module's internal scheduleActorCleanup
    // Since it's not exported, we test the observable behavior:
    // Stop the actor to make snapshot.status = "stopped" (not "done")
    // After ACTOR_CLEANUP_DELAY_MS, the actor should NOT be deleted

    // The actor is active (not done), so advance the timer
    vi.advanceTimersByTime(5 * 60 * 1000 + 1000);
    expect(getWorkflow("task-alive")).toBeDefined();
  });

  // --- scheduleActorCleanup: done actor is cleaned up ---

  it("done actor is cleaned up after the delay when it reaches a final state", () => {
    createTaskDraft("task-done");
    launchTask("task-done");
    // Transition to "completed" (a final state), which sets xstate status to "done"
    // The subscription callback sees status === "done" and calls scheduleActorCleanup
    sendEvent("task-done", { type: "CONFIRM" } as any);

    // Actor should still exist before the cleanup delay
    expect(getWorkflow("task-done")).toBeDefined();

    // Advance past the 5-minute cleanup delay
    vi.advanceTimersByTime(5 * 60 * 1000 + 1000);

    // Now the cleanup timer should have fired and deleted the done actor
    expect(getWorkflow("task-done")).toBeUndefined();
    expect(mockCloseStream).toHaveBeenCalledWith("task-done");
  });

  // --- SSE stream closed after cleanup ---

  it("SSE stream is closed when deleteWorkflow is called", () => {
    createTaskDraft("task-sse");
    deleteWorkflow("task-sse");
    expect(mockCloseStream).toHaveBeenCalledWith("task-sse");
  });

  // --- Race: cleanup scheduled while actor still running ---

  it("cleanup timer fires but actor is still active — actor survives", () => {
    createTaskDraft("task-race");
    launchTask("task-race");
    // Actor is running (status = "active"), cleanup should not remove it
    vi.advanceTimersByTime(5 * 60 * 1000 + 1000);
    expect(getWorkflow("task-race")).toBeDefined();
  });

  // --- restoreWorkflow returns undefined for unknown taskId ---

  it("restoreWorkflow returns undefined when no snapshot exists", () => {
    const result = restoreWorkflow("unknown-task-no-snapshot");
    expect(result).toBeUndefined();
  });

  // --- getAllWorkflows returns all registered actors ---

  it("getAllWorkflows returns a map of all registered actors", () => {
    createTaskDraft("task-m1");
    createTaskDraft("task-m2");
    const all = getAllWorkflows();
    expect(all.has("task-m1")).toBe(true);
    expect(all.has("task-m2")).toBe(true);
    expect(all.size).toBeGreaterThanOrEqual(2);
  });
});

describe("actor sweep and capacity", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    vi.useFakeTimers();
    for (const [id] of getAllWorkflows()) {
      deleteWorkflow(id);
    }
    vi.clearAllMocks();
  });

  afterEach(() => {
    vi.useRealTimers();
  });

  // Helper: create a mock actor directly in the actors Map to avoid
  // going through createTaskDraft (which triggers xstate machinery).
  function injectMockActor(
    taskId: string,
    contextOverrides: Record<string, any> = {},
  ): void {
    const actors = getAllWorkflows();
    const ctx = {
      taskId,
      status: "idle",
      updatedAt: new Date().toISOString(),
      retryCount: 0,
      qaRetryCount: 0,
      stageSessionIds: {},
      store: {},
      ...contextOverrides,
    };
    actors.set(taskId, {
      getSnapshot: () => ({ value: ctx.status, status: "active", context: ctx }),
      getPersistedSnapshot: () => ({}),
      subscribe: () => ({ unsubscribe: vi.fn() }),
      send: vi.fn(),
      start: vi.fn(),
      stop: vi.fn(),
    } as unknown as WorkflowActor);
  }

  // --- Pass 1: terminal actors ---

  it("sweepStaleActors removes terminal actors (completed, error, cancelled)", () => {
    injectMockActor("term-1", { status: "completed" });
    injectMockActor("term-2", { status: "error" });
    injectMockActor("term-3", { status: "cancelled" });
    injectMockActor("alive-1", { status: "running" });

    expect(getAllWorkflows().size).toBe(4);

    sweepStaleActors();

    expect(getAllWorkflows().has("term-1")).toBe(false);
    expect(getAllWorkflows().has("term-2")).toBe(false);
    expect(getAllWorkflows().has("term-3")).toBe(false);
    expect(getAllWorkflows().has("alive-1")).toBe(true);
    expect(getAllWorkflows().size).toBe(1);

    expect(mockCloseStream).toHaveBeenCalledWith("term-1");
    expect(mockCloseStream).toHaveBeenCalledWith("term-2");
    expect(mockCloseStream).toHaveBeenCalledWith("term-3");
    expect(flushSnapshotSync).toHaveBeenCalledTimes(3);
  });

  // --- Pass 1: actors that throw on getSnapshot are removed ---

  it("sweepStaleActors removes actors that throw on getSnapshot", () => {
    const actors = getAllWorkflows();
    actors.set("broken-1", {
      getSnapshot: () => { throw new Error("broken"); },
      getPersistedSnapshot: () => ({}),
      subscribe: () => ({ unsubscribe: vi.fn() }),
      send: vi.fn(),
      start: vi.fn(),
      stop: vi.fn(),
    } as unknown as WorkflowActor);

    sweepStaleActors();

    expect(getAllWorkflows().has("broken-1")).toBe(false);
    expect(mockCloseStream).toHaveBeenCalledWith("broken-1");
  });

  // --- Pass 2: stale blocked actors evicted when at capacity ---

  it("sweepStaleActors evicts stale blocked actors when at MAX_ACTORS capacity", () => {
    const twoHoursAgo = new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString();

    // Fill to exactly 200 actors: 199 running + 1 stale blocked
    for (let i = 0; i < 199; i++) {
      injectMockActor(`running-${i}`, { status: "running" });
    }
    injectMockActor("stale-blocked", {
      status: "blocked",
      updatedAt: twoHoursAgo,
    });

    expect(getAllWorkflows().size).toBe(200);

    sweepStaleActors();

    // Pass 1 removes nothing (no terminal). Pass 2 triggers because size >= 200.
    expect(getAllWorkflows().has("stale-blocked")).toBe(false);
    expect(getAllWorkflows().size).toBe(199);
  });

  // --- Pass 2: recently-updated blocked actors survive ---

  it("sweepStaleActors keeps recently-updated blocked actors even at capacity", () => {
    for (let i = 0; i < 199; i++) {
      injectMockActor(`running-${i}`, { status: "running" });
    }
    injectMockActor("fresh-blocked", {
      status: "blocked",
      updatedAt: new Date().toISOString(),
    });

    expect(getAllWorkflows().size).toBe(200);

    sweepStaleActors();

    // Fresh blocked actor should survive pass 2
    expect(getAllWorkflows().has("fresh-blocked")).toBe(true);
    expect(getAllWorkflows().size).toBe(200);
  });

  // --- Pass 3: stuck running actors evicted when still at capacity ---

  it("sweepStaleActors evicts stuck running actors (>2h no update) when at capacity", () => {
    const threeHoursAgo = new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString();

    for (let i = 0; i < 199; i++) {
      injectMockActor(`active-${i}`, { status: "running" });
    }
    injectMockActor("stuck-running", {
      status: "running",
      updatedAt: threeHoursAgo,
    });

    expect(getAllWorkflows().size).toBe(200);

    sweepStaleActors();

    // Pass 1: no terminal. Pass 2: no blocked. Pass 3: stuck running evicted.
    expect(getAllWorkflows().has("stuck-running")).toBe(false);
    expect(getAllWorkflows().size).toBe(199);
  });

  // --- Pass 3: idle actors are NOT evicted (only non-idle, non-blocked, non-terminal) ---

  it("sweepStaleActors does not evict idle actors even when stale and at capacity", () => {
    const threeHoursAgo = new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString();

    for (let i = 0; i < 199; i++) {
      injectMockActor(`active-${i}`, { status: "running" });
    }
    injectMockActor("old-idle", {
      status: "idle",
      updatedAt: threeHoursAgo,
    });

    expect(getAllWorkflows().size).toBe(200);

    sweepStaleActors();

    // idle is excluded from pass 3 (only targets non-idle, non-blocked, non-terminal)
    expect(getAllWorkflows().has("old-idle")).toBe(true);
  });

  // --- createTaskDraft throws when MAX_ACTORS exceeded ---

  it("createTaskDraft throws when MAX_ACTORS exceeded and sweep cannot free space", () => {
    // Fill with 200 non-terminal, fresh, running actors (un-sweepable)
    for (let i = 0; i < 200; i++) {
      injectMockActor(`cap-${i}`, { status: "running" });
    }

    expect(getAllWorkflows().size).toBe(200);

    expect(() => createTaskDraft("overflow-task")).toThrow(
      "Too many active tasks. Delete old tasks before creating new ones.",
    );

    expect(getAllWorkflows().has("overflow-task")).toBe(false);
  });

  // --- createTaskDraft succeeds after sweep frees terminal actors ---

  it("createTaskDraft succeeds when sweep frees terminal actors below capacity", () => {
    // 199 running + 1 terminal = 200 total
    for (let i = 0; i < 199; i++) {
      injectMockActor(`cap-${i}`, { status: "running" });
    }
    injectMockActor("terminal-freeup", { status: "completed" });

    expect(getAllWorkflows().size).toBe(200);

    // Should trigger sweep, free the terminal actor, then succeed
    const actor = createTaskDraft("new-task-after-sweep");
    expect(actor).toBeDefined();
    expect(getWorkflow("new-task-after-sweep")).toBe(actor);
    expect(getAllWorkflows().has("terminal-freeup")).toBe(false);
  });

  // --- stopSweepTimer clears the interval ---

  it("stopSweepTimer clears the sweep interval", () => {
    const clearIntervalSpy = vi.spyOn(globalThis, "clearInterval");

    stopSweepTimer();

    expect(clearIntervalSpy).toHaveBeenCalled();
    clearIntervalSpy.mockRestore();
  });

});
