// GitHub Actions CI/CD workflow template for target repositories.
// Generated by scriptPRCreation and written to .github/workflows/ if not already present.

export function generateCIWorkflow(): string {
  return `name: workflow-control CI/CD

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  ci:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm test || true
      - run: pnpm lint || true

  post-merge:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update Notion status to deployed
        if: env.NOTION_TOKEN != ''
        env:
          NOTION_TOKEN: \${{ secrets.NOTION_TOKEN }}
          NOTION_PAGE_ID: \${{ secrets.NOTION_PAGE_ID }}
        run: |
          if [ -n "$NOTION_PAGE_ID" ]; then
            curl -s -X PATCH "https://api.notion.com/v1/pages/$NOTION_PAGE_ID" \\
              -H "Authorization: Bearer $NOTION_TOKEN" \\
              -H "Content-Type: application/json" \\
              -H "Notion-Version: 2022-06-28" \\
              -d '{"properties":{"Status":{"select":{"name":"已完成"}}}}'
          fi

      - name: Slack notification
        if: env.SLACK_BOT_TOKEN != ''
        env:
          SLACK_BOT_TOKEN: \${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: \${{ secrets.SLACK_NOTIFY_CHANNEL_ID }}
        run: |
          curl -s -X POST https://slack.com/api/chat.postMessage \\
            -H "Authorization: Bearer $SLACK_BOT_TOKEN" \\
            -H "Content-Type: application/json" \\
            -d "{\\"channel\\":\\"$SLACK_CHANNEL_ID\\",\\"text\\":\\"[Deployed] Merged to main: \${{ github.event.head_commit.message }}\\"}"
`;
}
