// IR -> pipeline.ts codegen.
//
// Produces a single TypeScript module that:
//   1. Declares each stage's Input / Output interfaces under a namespace.
//   2. Emits one `__wire__*` dummy assignment per wire, forcing tsc to check
//      `from.type` assignable to `to.type`. On mismatch tsc reports TS2322
//      with the assignment line number, which validator/types.ts parses back
//      into a structured WIRE_TYPE_MISMATCH diagnostic.
//
// See docs/kernel-next-design.md §5.2 + §5.3 for the rationale (why dummy
// assignments instead of `extends ? true : never`).

import { createHash } from "node:crypto";
import type { PipelineIR, StageIR, PortIR } from "../ir/schema.js";

export interface WireMapEntry {
  line: number;                   // 1-based line number of the assignment
  fromStage: string;
  fromPort: string;
  toStage: string;
  toPort: string;
  fromType: string;
  toType: string;
}

export interface EmitResult {
  source: string;
  // Line -> wire map for diagnostic back-mapping. validator/types.ts uses
  // identifier name as primary key; line is kept for tsc error → wire lookup
  // when two wires happen to share a variable name collision (shouldn't
  // happen given our naming scheme, but cheap defense).
  wireByIdentifier: Map<string, WireMapEntry>;
  wireByLine: Map<number, WireMapEntry>;
}

// Wire identifier must be unambiguous: stage and port names may contain
// underscores, so the join-with-underscore form can collide (e.g. stage
// `a_b` port `c` vs stage `a` port `b_c` both encode to `a_b_c`). Append a
// short hash of the 4-tuple as disambiguator. The prefix keeps the name
// human-readable in tsc diagnostics; the hash guarantees uniqueness.
function wireIdentifier(fromStage: string, fromPort: string, toStage: string, toPort: string): string {
  const disambiguator = createHash("sha256")
    .update([fromStage, fromPort, toStage, toPort].join("\u0001"))
    .digest("hex")
    .slice(0, 8);
  return `__wire__${fromStage}_${fromPort}__TO__${toStage}_${toPort}__${disambiguator}`;
}

function emitPortBlock(ports: PortIR[], kind: "Inputs" | "Outputs"): string[] {
  if (ports.length === 0) {
    return [`    export interface ${kind} {}`];
  }
  const lines: string[] = [`    export interface ${kind} {`];
  for (const p of ports) {
    lines.push(`      ${p.name}: ${p.type};`);
  }
  lines.push(`    }`);
  return lines;
}

function emitStage(stage: StageIR): string[] {
  const lines: string[] = [];
  lines.push(`  export namespace ${stage.name} {`);
  lines.push(...emitPortBlock(stage.inputs, "Inputs"));
  lines.push(...emitPortBlock(stage.outputs, "Outputs"));
  lines.push(`  }`);
  return lines;
}

export function emitPipelineModule(ir: PipelineIR): EmitResult {
  const lines: string[] = [];
  lines.push(`// AUTOGENERATED by kernel-next/codegen/emit-ts. Do not edit.`);
  lines.push(`// Pipeline: ${ir.name}`);
  lines.push(``);
  lines.push(`export namespace Stages {`);
  for (const s of ir.stages) {
    lines.push(...emitStage(s));
  }
  lines.push(`}`);
  lines.push(``);

  // Wire assertions. Each assignment forces tsc to verify that the source
  // output type is assignable to the target input type.
  // Declaration shape:
  //   export const __wire__A_x__TO__B_x: Stages.B.Inputs["x"] =
  //     null as unknown as Stages.A.Outputs["x"];
  // On type mismatch tsc reports TS2322 at this line.
  const wireByIdentifier = new Map<string, WireMapEntry>();
  const wireByLine = new Map<number, WireMapEntry>();

  for (const w of ir.wires) {
    const ident = wireIdentifier(w.from.stage, w.from.port, w.to.stage, w.to.port);
    const toTypeLookup = `Stages.${w.to.stage}.Inputs["${w.to.port}"]`;
    const fromTypeLookup = `Stages.${w.from.stage}.Outputs["${w.from.port}"]`;

    // Design §7.3 — fanout type compatibility.
    //   from-fanout:   producer stage has `fanout`. Kernel auto-reshapes
    //                  each declared output T into T[] for downstream
    //                  consumption (§6.3 / §6.4). Wire source effective
    //                  type is Array<Outputs[port]>, declared is T.
    //   to-fanout:     consumer stage has `fanout` AND this wire targets
    //                  its fanout.input. Kernel iterates the source
    //                  array and feeds ONE element per virtual attempt,
    //                  so the declared input T is satisfied by T[][0].
    //   neither:       plain assignment, tsc checks declared types 1:1.
    //   both:          effects cancel — wire is T-to-T again.
    //
    // Without these wrap/unwrap transforms tsc would reject every fanout
    // pipeline with TS2322 (Reviewer concern C1 / plan §3 C1).
    const fromStage = ir.stages.find((s) => s.name === w.from.stage);
    const toStage = ir.stages.find((s) => s.name === w.to.stage);
    const fromIsFanout =
      (fromStage?.type === "agent" || fromStage?.type === "script") &&
      fromStage?.fanout != null;
    const toIsFanout =
      (toStage?.type === "agent" || toStage?.type === "script") &&
      toStage?.fanout != null &&
      toStage.fanout.input === w.to.port;

    // Build the right-hand value expression. The left-hand type
    // annotation never changes (always the declared Inputs[port]) —
    // only the source coercion adapts to fanout semantics.
    let rhsExpr: string;
    if (fromIsFanout && !toIsFanout) {
      // Producer aggregates T into T[]; downstream reads T[].
      rhsExpr = `[null as unknown as ${fromTypeLookup}]`;
    } else if (!fromIsFanout && toIsFanout) {
      // Downstream fans out the array; declared T input is one element.
      rhsExpr = `(null as unknown as ${fromTypeLookup})[0]!`;
    } else {
      // Plain or both-fanout (wrap + unwrap cancel).
      rhsExpr = `null as unknown as ${fromTypeLookup}`;
    }

    // Reserve the lines we're about to push and capture them for the map.
    // Keep the assignment on the next line after `export const`, matching
    // the primary signal line for tsc diagnostics on assignment.
    lines.push(`export const ${ident}: ${toTypeLookup} =`);
    const assignmentLine = lines.length + 1; // 1-based, line of the value expr
    lines.push(`  ${rhsExpr};`);

    // Resolve actual TS types from the port index for diagnostic payload.
    const fromPort = fromStage?.outputs.find((p) => p.name === w.from.port);
    const toPort = toStage?.inputs.find((p) => p.name === w.to.port);

    const entry: WireMapEntry = {
      line: assignmentLine,
      fromStage: w.from.stage,
      fromPort: w.from.port,
      toStage: w.to.stage,
      toPort: w.to.port,
      fromType: fromPort?.type ?? "<unknown>",
      toType: toPort?.type ?? "<unknown>",
    };
    wireByIdentifier.set(ident, entry);
    wireByLine.set(assignmentLine, entry);
    // Also map the declaration line (where tsc may anchor the error for
    // assignment-to-type errors).
    wireByLine.set(assignmentLine - 1, entry);
  }

  lines.push(``);
  return { source: lines.join("\n"), wireByIdentifier, wireByLine };
}
